In this Notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow.

We will see:
1. Introduction to tensors.
2. Getting information from tensors
3. Manupulating tensors
4. Tensors and Numpy
5. Using @tf.function (a way to speed up regular python functions)
6. Using GPU's with Tensorflow(or TPU's)
7. Excersises to try yourself!!

### Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__,)

2.21.0


In [2]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
## Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
## Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
## CReate a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
## Another matrix
another_matrix=tf.constant([[10.,7.],[6.,7.],[8.,9.]],dtype=tf.float16) # specify the data type with dtype parameter.
another_matrix
# using dtype =16 saves space and memory.

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 6.,  7.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim ## No of elements in shape.

2

In [10]:
## Lets create tensor
tensor=tf.constant([[[1,2,3,],[4,5,5]],[[6,7,8],[11,22,33]],[[12,13,14],[13,23,34]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  5]],

       [[ 6,  7,  8],
        [11, 22, 33]],

       [[12, 13, 14],
        [13, 23, 34]]], dtype=int32)>

In [11]:
tensor.ndim

3

##### Creating tensors with tf.variable

In [12]:
## Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
## To change
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [16]:
#### Creating Random Tensors.
#### Random tensors are tensors of some abitrary size which contain random numbers.

random_1=tf.random.Generator.from_seed(7) #set seed for reproductivity
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [17]:
random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [ ]:
## Are they equal?
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
## Shufffling the order of elements in a tensor.
## Shuffle the tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning.)
not_shuffled=tf.constant([[10,7],
[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed=42) #Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#### IT looks like if we want our shuffled tensors to be in the same order, we've got we the global level random seed as well as the operation level random seed:

-> If both the global and operational seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
## Other ways to make tensors.
## Create tensor of all ones.
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.ones(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
## You can turn numpy arrays into tensors.
# THE main diff btwn these is that tensors can be run on a GPU much faster for numerical computing.
import numpy as np 
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B ## Now its converted to a tensor.

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2*3*4

24

In [ ]:
A.ndim

3

#### Getting Information from tensors. (Tensor Attributes)
1) Shape.
2) Rank.
3) Axis or dimension.
4) Size.

In [ ]:
## Multiply also works
tensor*10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  50]],

       [[ 60,  70,  80],
        [110, 220, 330]],

       [[120, 130, 140],
        [130, 230, 340]]], dtype=int32)>

In [ ]:
## Subs /Add also work but the original is unchanged
tensor-10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[-9, -8, -7],
        [-6, -5, -5]],

       [[-4, -3, -2],
        [ 1, 12, 23]],

       [[ 2,  3,  4],
        [ 3, 13, 24]]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  5]],

       [[ 6,  7,  8],
        [11, 22, 33]],

       [[12, 13, 14],
        [13, 23, 34]]], dtype=int32)>

In [ ]:
## WE can use the tensorflow built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  50]],

       [[ 60,  70,  80],
        [110, 220, 330]],

       [[120, 130, 140],
        [130, 230, 340]]], dtype=int32)>

In [18]:
rank4_tensors=tf.zeros(shape=[2,3,4,5])
rank4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
## Indexing tensors
## Get the first 2 elements of each dimension
rank4_tensors[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
## Add in extra dimension to our rank 
rank4_tensors=rank4_tensors[...,tf.newaxis]
rank4_tensors

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

In [21]:
#### ALternative to tf.axis
# tf.expand_dims(rank4_tensors,axis=-1)
tf.expand_dims(rank4_tensors,axis=0)

<tf.Tensor: shape=(1, 2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.],
           [0.]],

          [[0.],
           [0.],
           [0.],
           [0.]

### MATRIX MULTIPLICATION
It is one of the most common operations.

In [23]:
tensor=tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [24]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor  #Element wise multiplication.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [26]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

There are two rules our tensors(or matrices) need to fulfil if we're going to matrix multiply them:

1. the inner dimension must match.
2. The resulting matrix has the shape of the inner dimension.

In [ ]:
## IN matrix mul, the inner one shoud match and new matrix will be the size of other outer one.
## [3,4] & [4,2] , here 4-4 is matching and new matrix will be [3,2].
## To reshape we can use tf.reshape(X,shape=(3,4)).
## To generate mul of transpose matrix tf.matmul(tf.transpose(X),Y).


#### Dot product
matrix mul is also refer as dot pdt and can be performed using tf.matmul() or tf.tesnordot().

In [ ]:
## Change the datatype of tensors
