#### Changing the datatype of a tensor.

In [1]:
import tensorflow as tf

In [2]:
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [3]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [4]:
#### To change from float32 to float16 (reduced precision)
B=tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [5]:
D=tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [6]:
#### Int 32 to float 32
E=tf.cast(C,dtype=tf.float32)
E.dtype

tf.float32

#### Aggregating Tensors= condensing then from multiple values down to a smaller amount of values.

In [7]:
## Get the absolute values.
D=tf.constant([-7,-10])
D
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### Lets go through the following forms of aggregation:
1) get the min
2) get the max
3) get the mean of a tensor
4) get the sum of a tensor

In [8]:
import numpy as np

In [9]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([74, 47, 65, 69,  6,  9, 29, 88, 63, 31,  2, 41, 50, 25, 14, 67, 30,
        2, 63, 90, 98, 89, 38, 76, 96, 92, 96, 86, 82, 78, 42, 49, 61, 73,
       23, 96, 82, 16, 91, 88, 69, 88, 23, 81, 37, 90, 68, 16, 39,  3],
      dtype=int32)>

In [10]:
## Find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
np.min(E)

np.int32(2)

In [12]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [13]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=56>

In [14]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2831>

In [15]:
import sys
print(sys.executable)

c:\Users\Asus\Desktop\TensorFlow\.venv\Scripts\python.exe


In [16]:
import tensorflow_probability as tfp 
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=915>

In [17]:
## Find the positional max and min
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [18]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [19]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [20]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [21]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

#### Squeezing a tensor (removing all single dimension)

In [23]:
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [24]:
G_squeezed=tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
        0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
        0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
        0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
        0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
        0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
        0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
       dtype=float32)>,
 TensorShape([50]))

#### One hot encoding tensors

In [25]:
some_list=[0,1,2,3] # could be red,green,blue,purple

## One hot encoding our list of indexes
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [26]:
## Specify custom values for one hot encoding.
tf.one_hot(some_list,depth=4,on_value="I love deep learning", off_value="Also I like machine learning")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'Also I like machine learning',
        b'Also I like machine learning', b'Also I like machine learning'],
       [b'Also I like machine learning', b'I love deep learning',
        b'Also I like machine learning', b'Also I like machine learning'],
       [b'Also I like machine learning', b'Also I like machine learning',
        b'I love deep learning', b'Also I like machine learning'],
       [b'Also I like machine learning', b'Also I like machine learning',
        b'Also I like machine learning', b'I love deep learning']],
      dtype=object)>

#### Squaring, Log, Square Root

In [27]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32)) ## It can be an int type.

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [29]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#### Tensors and Numpy
TensorFlow interacts Beautifully with Numpy arrays.

In [30]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [31]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [32]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [33]:
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

#### Finding access to GPU's

In [34]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [35]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [36]:
import tensorflow as tf

print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

2.21.0
[]


NOTE: If you have access to a CUDA-enabled GPU,Tensorflow will automatically use it whenver possible.

### Steps in modelling with TensorFlow
Now we know what data we have as well as the input and output shapes, let's see how we'd build a neural network to model it.

In TensorFlow, there are typically 3 fundamental steps to creating and training a model.

Creating a model - piece together the layers of a neural network yourself (using the Functional or Sequential API) or import a previously built model (known as transfer learning).
Compiling a model - defining how a models performance should be measured (loss/metrics) as well as defining how it should improve (optimizer).
Fitting a model - letting the model try to find patterns in the data (how does X get to y).

In [ ]:
#### In between things we have already done in the dl and ml repo so as this a 22hr video will skip those as we have already done them
## &  we should not waste anymore time in doing these things again only a little bit syntax change might be there beacuse we are using tensorflow this time
## But its mostly same logic and every thing.

#### When we are coming models by making layers then the one that has low mse and mae will win.

NOTE: One of the main goals should be to minimize the time between your experiments. The more experiments you do, the more things you'll figure out which don't work and in turn,get closer to figure out what does works. Remember the machine learning praction's moto: Experiment, Experiment, Experiment.

##### Tracking your experiments:
one really good habit in ml is to track the results of your experiments.
and when doing so, it can be tedious if you're running lots of experiments.
Luckily, there are tools to help us!

TOOLS:
1) TensorBoard - It is a component of the Tensorflow library to help track modelling experiments.
2) Weights & Biases - A tool for tracking all kinds of ml experiments .



#### Running experiments to improve a model
After seeing the evaluation metrics and the predictions your model makes, it's likely you'll want to improve it.

Again, there are many different ways you can do this, but 3 of the main ones are:

Get more data - get more examples for your model to train on (more opportunities to learn patterns).
Make your model larger (use a more complex model) - this might come in the form of more layers or more hidden units in each layer.
Train for longer - give your model more of a chance to find the patterns in the data.
Since we created our dataset, we could easily make more data but this isn't always the case when you're working with real-world datasets.

So let's take a look at how we can improve our model using 2 and 3.

To do so, we'll build 3 models and compare their results:

1) model_1 - same as original model, 1 layer, trained for 100 epochs.
2) model_2 - 2 layers, trained for 100 epochs.
3) model_3 - 2 layers, trained for 500 epochs.