In this Notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow.

We will see:
1. Introduction to tensors.
2. Getting information from tensors
3. Manupulating tensors
4. Tensors and Numpy
5. Using @tf.function (a way to speed up regular python functions)
6. Using GPU's with Tensorflow(or TPU's)
7. Excersises to try yourself!!

### Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__,)

2.21.0


In [3]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
## Check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
## Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
## CReate a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
## Another matrix
another_matrix=tf.constant([[10.,7.],[6.,7.],[8.,9.]],dtype=tf.float16) # specify the data type with dtype parameter.
another_matrix
# using dtype =16 saves space and memory.

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 6.,  7.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim ## No of elements in shape.

2

In [11]:
## Lets create tensor
tensor=tf.constant([[[1,2,3,],[4,5,5]],[[6,7,8],[11,22,33]],[[12,13,14],[13,23,34]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  5]],

       [[ 6,  7,  8],
        [11, 22, 33]],

       [[12, 13, 14],
        [13, 23, 34]]], dtype=int32)>

In [12]:
tensor.ndim

3

##### Creating tensors with tf.variable

In [15]:
## Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
## To change
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [26]:
#### Creating Random Tensors.
#### Random tensors are tensors of some abitrary size which contain random numbers.

random_1=tf.random.Generator.from_seed(7) #set seed for reproductivity
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [24]:
random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [27]:
## Are they equal?
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [29]:
## Shufffling the order of elements in a tensor.
## Shuffle the tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning.)
not_shuffled=tf.constant([[10,7],
[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) ## set the behaviour
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>