#### Changing the datatype of a tensor.

In [1]:
import tensorflow as tf

In [2]:
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [3]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [4]:
#### To change from float32 to float16 (reduced precision)
B=tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [5]:
D=tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [6]:
#### Int 32 to float 32
E=tf.cast(C,dtype=tf.float32)
E.dtype

tf.float32

#### Aggregating Tensors= condensing then from multiple values down to a smaller amount of values.

In [8]:
## Get the absolute values.
D=tf.constant([-7,-10])
D
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### Lets go through the following forms of aggregation:
1) get the min
2) get the max
3) get the mean of a tensor
4) get the sum of a tensor

In [9]:
import numpy as np

In [10]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([83, 56, 21, 90, 84, 41, 39, 97, 84, 68, 21, 22, 68, 41, 19, 61, 69,
       30, 82, 14, 16, 66, 65, 67, 14, 93, 29, 17, 56, 25, 43, 83, 10, 80,
       68, 77, 23, 97, 87, 10, 19, 34, 62, 81, 31, 26, 92, 80, 60,  2],
      dtype=int32)>

In [12]:
## Find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [13]:
np.min(E)

np.int32(2)

In [14]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [15]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [16]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2603>

In [19]:
import sys
print(sys.executable)

c:\Users\Asus\Desktop\TensorFlow\.venv\Scripts\python.exe


In [25]:
import tensorflow_probability as tfp 
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=815>